version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass Thien1997 --appendonly yes --maxmemory 2gb --maxmemory-policy allkeys-lru
    restart: always
    networks:
      - mystic_network

volumes:
  redis_data:
    driver: local

networks:
  mystic_network:
    driver: bridge 